import supabase
from supabase_client import supabase


# Data for 20 employees
employees = [
    {
        "id": "1001",
        "name": "BILL GATES",
        "department": "Technology",
        "joining_year": 1975,
        "total_attendance": 40,
        "grade": "A",
        "experience_years": 45,
    },
    {
        "id": "1002",
        "name": "ELON MUSK",
        "department": "Engineering",
        "joining_year": 2002,
        "total_attendance": 50,
        "grade": "A+",
        "experience_years": 21,
    },
    {
        "id": "1003",
        "name": "SUNDAR PICHAI",
        "department": "Product Management",
        "joining_year": 2004,
        "total_attendance": 38,
        "grade": "A",
        "experience_years": 20,
    },
    {
        "id": "1004",
        "name": "TIM COOK",
        "department": "Operations",
        "joining_year": 1998,
        "total_attendance": 42,
        "grade": "A",
        "experience_years": 26,
    },
    {
        "id": "1005",
        "name": "SATYA NADELLA",
        "department": "Cloud",
        "joining_year": 1992,
        "total_attendance": 44,
        "grade": "A",
        "experience_years": 32,
    },
    {
        "id": "1006",
        "name": "JEFF BEZOS",
        "department": "Logistics",
        "joining_year": 1994,
        "total_attendance": 35,
        "grade": "B+",
        "experience_years": 30,
    },
    {
        "id": "1007",
        "name": "MUBASHIR SHAIKH",
        "department": "AI Research",
        "joining_year": 2023,
        "total_attendance": 48,
        "grade": "A+",
        "experience_years": 1,
    },
    {
        "id": "1008",
        "name": "MARK ZUCKERBERG",
        "department": "Social Media",
        "joining_year": 2004,
        "total_attendance": 37,
        "grade": "B",
        "experience_years": 20,
    },
    {
        "id": "1009",
        "name": "OPRAH WINFREY",
        "department": "Media",
        "joining_year": 1985,
        "total_attendance": 50,
        "grade": "A",
        "experience_years": 39,
    },
    {
        "id": "1010",
        "name": "BARACK OBAMA",
        "department": "Public Relations",
        "joining_year": 2008,
        "total_attendance": 43,
        "grade": "A",
        "experience_years": 16,
    },
    {
        "id": "1011",
        "name": "CRISTIANO RONALDO",
        "department": "Sports",
        "joining_year": 2003,
        "total_attendance": 41,
        "grade": "A",
        "experience_years": 21,
    },
    {
        "id": "1012",
        "name": "LIONEL MESSI",
        "department": "Sports",
        "joining_year": 2004,
        "total_attendance": 40,
        "grade": "A",
        "experience_years": 20,
    },
    {
        "id": "1013",
        "name": "TAYLOR SWIFT",
        "department": "Music",
        "joining_year": 2006,
        "total_attendance": 39,
        "grade": "A",
        "experience_years": 18,
    },
    {
        "id": "1014",
        "name": "ADELE",
        "department": "Music",
        "joining_year": 2008,
        "total_attendance": 36,
        "grade": "A-",
        "experience_years": 16,
    },
    {
        "id": "1015",
        "name": "EMMA WATSON",
        "department": "Education",
        "joining_year": 2014,
        "total_attendance": 32,
        "grade": "B+",
        "experience_years": 10,
    },
    {
        "id": "1016",
        "name": "DWAYNE JOHNSON",
        "department": "Fitness",
        "joining_year": 2001,
        "total_attendance": 47,
        "grade": "A+",
        "experience_years": 23,
    },
    {
        "id": "1017",
        "name": "KEANU REEVES",
        "department": "Film",
        "joining_year": 1990,
        "total_attendance": 34,
        "grade": "B+",
        "experience_years": 34,
    },
    {
        "id": "1018",
        "name": "LEONARDO DICAPRIO",
        "department": "Film",
        "joining_year": 1993,
        "total_attendance": 35,
        "grade": "A-",
        "experience_years": 31,
    },
    {
        "id": "1019",
        "name": "SHAH RUKH KHAN",
        "department": "Film",
        "joining_year": 1992,
        "total_attendance": 40,
        "grade": "A",
        "experience_years": 32,
    },
    {
        "id": "1020",
        "name": "VIRAT KOHLI",
        "department": "Sports",
        "joining_year": 2008,
        "total_attendance": 42,
        "grade": "A",
        "experience_years": 16,
    },
]


# Insert into Supabase
for emp in employees:
    res = supabase.table("emp").insert(emp).execute()
    print(f"Inserted {emp['name']} successfully.")
