FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git \
    libopenblas-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

# dlib-bin = pre-compiled, no cmake, no memory spike
RUN pip install --no-cache-dir dlib-bin
RUN pip install --no-cache-dir git+https://github.com/ageitgey/face_recognition_models
RUN pip install --no-cache-dir face-recognition==1.3.0
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 10000

CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:10000", "app:app"]